### ISSUE TITLE
Windows <-> Mac. CRLF 이슈

### ISSUE THREAD

**Issue by ysle0** [JuHyun419/one-line-course#38]
- Windows -> 라인 바꿈 문자를 CR(Carrage-Return) 과 LF(Line-Feed) 문자 둘다 사용.
- Mac&Linux -> 라인 바꿈 문자를 LF 만 사용.

-> Windows 와 Mac, Linux(Unix) 같은 파일 사용 시에 라인 바꿈문자 문제가 생긴다.

 Git 은 commit 시에 자동으로 CRLF -> LF 변환, 반대로 checkout 시에 자동으로 LF -> CRLF 변환.

<Windows>
git config --global core.autocrlf true

-> 저장소에 커밋할 때는 자동으로 LF 로, 저장소에서 체크아웃 할 때는 자동으로 crlf(윈도우 default 방식) 으로 바꾸게된다

<mac/linux>
git config --global core.autocrlf input

-> crlf 를 기본으로 사용하지 않으므로, 커밋 시에만 CRLF 를 LF 로 자동으로 바꾸기만 한다 (체크아웃은 LF -> LF 로 변경 X)

**Comment by JuHyun419** [comment]
👍
