### ISSUE TITLE
feat(front): ENV 파일을 parcel 번들러에서 사용 불가능한 문제

### ISSUE THREAD

**Issue by ysle0** [JuHyun419/one-line-course#50]
*.env 파일이 사용 불가능해서 찾아보니깐
parcel 에서는 exposing security rule 로 .env 의 직접 접근 (process.env) 이 불가능 하여, 
package.json 과 같은 directory 의 .env 파일을 정의하여 사용하는 것을 확인.

https://parceljs.org/env.html
https://github.com/parcel-bundler/parcel/issues/2299
https://github.com/parcel-bundler/parcel/issues/2310
https://github.com/parcel-bundler/parcel/issues/3537

**Comment by JuHyun419** [comment]
*.env 파일이 환경설정? 같은거 설정하는 파일인가요???
